2018-05-31 13:50:36,464  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-05-31 13:50:36――System.NullReferenceException：未将对象引用设置到对象的实例。――堆栈信息：   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.InitOrderData(T_AccountBasic account, List`1 products, SaveSpecialtyOrderDTO dto, List`1 productForSpecialtyList, List`1 productForSpecialtyVarietiesList, List`1& orderlist, List`1& orderItemList, List`1& orderProcessList) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 870
   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 750
   在 Castle.Proxies.Invocations.IT_OrderItemForSpecialtyService_SaveSpcialtyOrder.InvokeMethodOnTarget()
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 WisdomScenic.Project.Infrastructure.Castle.QCachingInterceptor.Intercept(IInvocation invocation) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.Infrastructure\Castle\AopForCache\QCachingInterceptor.cs:行号 35
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 Castle.Proxies.IDisposableProxy_11.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto)
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<>c__DisplayClass10_0.<SaveSpcialtyOrder>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 135
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<SaveSpcialtyOrder>d__10.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 133
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()WisdomScenic.Project.BLL
2018-05-31 13:51:29,578  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-05-31 13:51:29――System.NullReferenceException：未将对象引用设置到对象的实例。――堆栈信息：   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.InitOrderData(T_AccountBasic account, List`1 products, SaveSpecialtyOrderDTO dto, List`1 productForSpecialtyList, List`1 productForSpecialtyVarietiesList, List`1& orderlist, List`1& orderItemList, List`1& orderProcessList) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 870
   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 750
   在 Castle.Proxies.Invocations.IT_OrderItemForSpecialtyService_SaveSpcialtyOrder.InvokeMethodOnTarget()
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 WisdomScenic.Project.Infrastructure.Castle.QCachingInterceptor.Intercept(IInvocation invocation) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.Infrastructure\Castle\AopForCache\QCachingInterceptor.cs:行号 35
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 Castle.Proxies.IDisposableProxy_11.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto)
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<>c__DisplayClass10_0.<SaveSpcialtyOrder>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 135
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<SaveSpcialtyOrder>d__10.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 133
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()WisdomScenic.Project.BLL
2018-05-31 14:13:20,152  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-05-31 14:13:20――System.NullReferenceException：未将对象引用设置到对象的实例。――堆栈信息：   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.InitOrderData(T_AccountBasic account, List`1 products, SaveSpecialtyOrderDTO dto, List`1 productForSpecialtyList, List`1 productForSpecialtyVarietiesList, List`1& orderlist, List`1& orderItemList, List`1& orderProcessList) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 870
   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 750
   在 Castle.Proxies.Invocations.IT_OrderItemForSpecialtyService_SaveSpcialtyOrder.InvokeMethodOnTarget()
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 WisdomScenic.Project.Infrastructure.Castle.QCachingInterceptor.Intercept(IInvocation invocation) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.Infrastructure\Castle\AopForCache\QCachingInterceptor.cs:行号 35
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 Castle.Proxies.IDisposableProxy_11.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto)
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<>c__DisplayClass10_0.<SaveSpcialtyOrder>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 135
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<SaveSpcialtyOrder>d__10.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 133
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()WisdomScenic.Project.BLL
2018-05-31 14:14:51,975  WisdomScenic.Project.Attributes.API.ApiExceptionFilter : 2018-05-31 14:14:51――System.NullReferenceException：未将对象引用设置到对象的实例。――堆栈信息：   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.InitOrderData(T_AccountBasic account, List`1 products, SaveSpecialtyOrderDTO dto, List`1 productForSpecialtyList, List`1 productForSpecialtyVarietiesList, List`1& orderlist, List`1& orderItemList, List`1& orderProcessList) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 870
   在 WisdomScenic.Project.DAL.Orders.T_OrderItemForSpecialtyService.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.BLL\Orders\T_OrderItemForSpecialtyService.cs:行号 750
   在 Castle.Proxies.Invocations.IT_OrderItemForSpecialtyService_SaveSpcialtyOrder.InvokeMethodOnTarget()
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 WisdomScenic.Project.Infrastructure.Castle.QCachingInterceptor.Intercept(IInvocation invocation) 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.Infrastructure\Castle\AopForCache\QCachingInterceptor.cs:行号 35
   在 Castle.DynamicProxy.AbstractInvocation.Proceed()
   在 Castle.Proxies.IDisposableProxy_11.SaveSpcialtyOrder(SaveSpecialtyOrderDTO dto)
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<>c__DisplayClass10_0.<SaveSpcialtyOrder>b__0() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 135
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 WisdomScenic.Project.WebApi.Areas.Order.OrderItemForSpecialtyController.<SaveSpcialtyOrder>d__10.MoveNext() 位置 E:\Project\Wisdom.Trip\Web.Service\WisdomScenic.Project.WebApi\Areas\Order\OrderItemForSpecialtyController.cs:行号 133
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()WisdomScenic.Project.BLL
